incident_type_to_risk = {
    "child abandonment": 1,
    "client aggression towards another person": 1,
    "client aggression towards property": 3,
    "client death (offsite)": 1,
    "client death (onsite)": 4,
    "client missing": 4,
    "concern for welfare of a child": 4,
    "covid-19 confirmed": 5,
    "exposure": 1,
    "homicide (Threat or attempt)": 3,
    "illegal activity on premises": 5,
    "injury": 2,
    "media/3rd party contact": 3,
    "medical emergency": 2,
    "mental health emergency": 2,
    "security concern": 1,
    "suicide attempt": 3,
    "suspected or actual breach of privacy": 3,
    "suspicion/allegation of abuse towards or against client": 3,
    "suspicion/allegation of child abuse - child is not a client": 4,
    "other": 1,
}

program_to_risk = {
    "child care hub": 5,
    "child support": 5,
    "compass": 1,
    "counselling": 1,
    "croydon": 4,
    "DCRT": 3,
    "dropin child care": 3,
    "employment resource center": 1,
    "family access": 2,
    "family resource network": 3,
    "intensive case management": 5,
    "LINC": 2,
    "mindful moments": 4,
    "outreach counselling": 3,
    "providence (community housing)": 4,
    "sheriff king home": 1,
    "the maple (community housing)": 4,
    "transitional housing": 1,
}

response_to_risk = {
    "called child welfare": 5,
    "evacuation": 4,
    "first-aid provided": 4,
    "infection prevention protocol": 2,
    "mental health assessment": 5,
    "naloxone administered": 5,
    "person barred/access restricted": 2,
    "safety assessment": 5,
    "safety planning": 5,
    "other": 2,
}
